// Board is generated by a boardGenerator that takes in:
// width
// height
// #mines

// Board can have the following prop:
// array of arrays with cell values

// Board can have state:
//

import {connect} from 'react-redux';
import Cell from './Cell.jsx';

function mapStateToProps(state) {
  const {boardArr} = state;
  return {boardArr}
}

function Board ({boardArr}) {
  return (
    <div id="board">
      {boardArr.map((boardRow, rowIndex) => {
        return <div key={`${rowIndex}`}>{boardRow.map((cell, colIndex) => {
          return <Cell
            key={`${rowIndex} ${colIndex}`}
            isCovered={cell.isCovered}
            value={cell.value}
          />
        })}</div>
      })}
    </div>
  );
}

export default connect(mapStateToProps, null)(Board);